apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-go-service-prod
resources:
  - ../../base
patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
configMapGenerator:
  - name: sample-go-service-config
    behavior: replace
    envs:
      - configmap.yaml
images:
  - name: docker.io/kuberpull/sample-go-service
    newTag: sha-5f19e10fe41091b5f5549bca29bc7a5241244246
    newName: docker.io/kuberpull/sample-go-service
