apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-go-service-dev
resources:
  - ../../base
patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
configMapGenerator:
  - name: sample-go-service-config
    behavior: replace
    envs:
      - configmap.yaml
images:
  - name: docker.io/kuberpull/sample-go-service
    newName: docker.io/kuberpull/sample-go-service
    newTag: sha-5e2b60bd76eef2ee35f6b0eb0fe5e514565658ca
