apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-service
spec:
  template:
    spec:
      containers:
        - name: sample-go-service
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
