apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-service
  labels:
    app.kubernetes.io/name: sample-go-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: enterprise-kubernetes-delivery-platform
    app.kubernetes.io/version: 0.0.0
spec:
  replicas: 1
  revisionHistoryLimit: 5 # Keeps recent ReplicaSets available for fast rollback after a bad rollout.
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # Keeps all current capacity serving while replacement pods become ready.
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-go-service
  template:
    metadata:
      labels:
        app: sample-go-service
        app.kubernetes.io/name: sample-go-service
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: enterprise-kubernetes-delivery-platform
        app.kubernetes.io/version: 0.0.0
        version: stable
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30 # Gives the app time to finish in-flight requests before pod termination.
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sample-go-service
          image: docker.io/ohanyere/sample-go-service:replace-me
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: sample-go-service-config
            - secretRef:
                name: sample-go-service-secret
                optional: true
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
